/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c CchAdaptor -a CchAdaptor.h:CchAdaptor.cpp polkit/org.condrescontrolcenter.pacmanhelper.xml
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CCHADAPTOR_H
#define CCHADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.condrescontrolcenter.pacmanhelper
 */
class CchAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.condrescontrolcenter.pacmanhelper")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.condrescontrolcenter.pacmanhelper\">\n"
"    <method name=\"syncdb\"/>\n"
"    <signal name=\"syncdbcompleted\"/>\n"
"  </interface>\n"
        "")
public:
    CchAdaptor(QObject *parent);
    virtual ~CchAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void syncdb();
Q_SIGNALS: // SIGNALS
    void syncdbcompleted();
};

#endif
