/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c CchClient -p CchClient.h:CchClient.cpp polkit/org.condrescontrolcenter.pacmanhelper.xml
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CCHCLIENT_H
#define CCHCLIENT_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.condrescontrolcenter.pacmanhelper
 */
class CchClient: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.condrescontrolcenter.pacmanhelper"; }

public:
    CchClient(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~CchClient();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> syncdb()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("syncdb"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void syncdbcompleted();
};

namespace org {
  namespace condrescontrolcenter {
    typedef ::CchClient pacmanhelper;
  }
}
#endif
